---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable

  check-file-headers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Check header
      run: python ./check_header.py
      shell: bash

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12", "windows-2022"]
        python_version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Run tests
      run: python ./run_tests.py
      shell: bash
